name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install Lua
        run: sudo apt-get install -y lua5.1
      -
        name: Lint
        run: |
          lua componentlint.lua tests/auto_*