name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - name: Cache Lua
        id: cache-lua
        uses: actions/cache@v1
        with:
          path: .lua
          key: ${{ runner.os }}-lua-5.2
      -
        name: Install Lua
        if: steps.cache-lua.outputs.cache-hit != 'true'
        uses: leafo/gh-actions-lua@v3
        with:
          luaVersion: "5.2"
      -
        name: Lint
        run: |
          lua componentlint.lua tests/auto_*